import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runSceneBatches} from './public/scene-workflow.mjs';
import {scenePromptRows} from './public/scene-prompts.mjs';
import {sceneCompletionError,renderSceneCards} from './public/scene-cards.mjs';
const bible=JSON.parse(await readFile('studio/public/schoolboy.preset.json','utf8'));
const main={name:'Tích',description:bible.identity,bible};
const channel={type:'mascot',characters:[main],visualStyle:'Ink.'};
const project=()=>({step:5,script:'A boy holds an empty wallet.',voiceSeconds:4,clipSeconds:4,mainCharacters:[main],rosterConfirmed:true,roster:{[main.name]:main.description},scenes:[]});
const row=(characters,noCharacter=false)=>({visual:'A boy holds a wallet.',prompt:'A boy holds an empty wallet.',overlay:'',sfx:'',characters,background:'',noCharacter});
test('P1 empty characters retain exact main identity; explicit noCharacter excludes it without mutating state',()=>{const p=project();p.scenes=[{index:1,narration:p.script,...row([])}];const original=JSON.stringify(p);assert(scenePromptRows(channel,p)[0].image_prompt.includes(bible.identity));assert.equal(JSON.stringify(p),original);p.scenes[0].noCharacter=true;assert(!scenePromptRows(channel,p)[0].image_prompt.includes(bible.identity));p.scenes[0].noCharacter=false;p.scenes[0].characters=[main.name];assert(scenePromptRows(channel,p)[0].image_prompt.includes(bible.identity));});
test('P1 unknown character retries once then saves red flag, never guesses or emits a character-free prompt',async()=>{const p=project(),calls=[];await runSceneBatches(p,{channel,save:async()=>{},generate:async(action,context)=>{calls.push({action,context});return action==='sceneTags'?{tagsByIndex:[{index:1,expression:bible.expressions[0].tag,pose:bible.poses[0].tag,camera:'wide',graphics:[],summary:''}]}:{scenes:[row(['Nam'])]};}});assert.equal(calls.filter(c=>c.action==='scenes').length,2);assert.deepEqual(calls.find(c=>c.action==='scenes').context.rosterNames,[main.name]);assert(!JSON.stringify(calls).includes(bible.identity));assert.deepEqual(p.scenes[0].characters,['Nam']);assert(p.scenes[0].invalidCharacters);const output=scenePromptRows(channel,p)[0];assert(output.warnings.includes('invalidCharacters'));assert.equal(output.image_prompt,'');assert(sceneCompletionError(p));assert(renderSceneCards(channel,p,{esc:s=>String(s??''),btn:()=>''}).includes('Nam'));});
test('P1 corrected retry saves valid scene; explicit noCharacter survives generation',async()=>{for(const noCharacter of [false,true]){const p=project();let calls=0;await runSceneBatches(p,{channel,save:async()=>{},generate:async action=>action==='sceneTags'?{tagsByIndex:[{index:1,expression:bible.expressions[0].tag,pose:bible.poses[0].tag,camera:'wide',graphics:[],summary:''}]}:{scenes:[row(calls++===0?['Nam']:[],noCharacter)]}});assert.equal(calls,2);assert.equal(p.scenes[0].noCharacter,noCharacter);assert(!p.scenes[0].invalidCharacters);assert.equal(scenePromptRows(channel,p)[0].image_prompt.includes(bible.identity),!noCharacter);}});

test('repair characters unlocks prompt and completion, rejects unknown selection atomically',async()=>{
 const {updateSceneCharacters}=await import('./public/scene-character.mjs');const p=project();p.done=true;p.approved=[0,5];p.scenes=[{index:1,narration:p.script,...row(['Nam']),expression:bible.expressions[0].tag,pose:bible.poses[0].tag,camera:'wide',invalidCharacters:true,characterError:'Nam'}];
 const before=structuredClone(p);assert.throws(()=>updateSceneCharacters(channel,p,0,{characters:['Unknown'],noCharacter:false}));assert.deepEqual(p,before);
 updateSceneCharacters(channel,p,0,{characters:[main.name],noCharacter:false});assert(!p.scenes[0].invalidCharacters);assert(!p.scenes[0].characterError);assert(!p.done);assert.deepEqual(p.approved,[0]);const result=scenePromptRows(channel,p)[0];assert(result.image_prompt.includes(bible.identity));assert(!result.warnings.includes('invalidCharacters'));assert.equal(sceneCompletionError(p,channel),'');
 const html=renderSceneCards(channel,p,{esc:s=>String(s??''),btn:(label,action,cls,attrs)=>`<button data-action="${action}" ${attrs}>${label}</button>`});assert(html.includes('data-scene-character="0"'));assert(html.includes(`value="${main.name}" checked`));assert(html.includes('data-scene-no-character="0"'));assert(html.includes('data-action="regenerate-scene"'));
 updateSceneCharacters(channel,p,0,{characters:[],noCharacter:true});assert(!scenePromptRows(channel,p)[0].image_prompt.includes(bible.identity));assert.equal(sceneCompletionError(p,channel),'');
});
test('regenerate one scene uses only its code window and keeps other scenes and animations',async()=>{
 const {regenerateScene}=await import('./public/scene-workflow.mjs');const p=project();p.script='First boy waits. Second boy reacts. Third boy smiles.';p.voiceSeconds=12;p.scenes=Array.from({length:3},(_,i)=>({index:i+1,narration:['First boy waits.','Second boy reacts.','Third boy smiles.'][i],...row([main.name]),expression:bible.expressions[0].tag,pose:bible.poses[0].tag,camera:'wide',summary:'He waits.'}));p.animations={1:'Move first',2:'Move second',3:'Move third'};p.approved=[5];p.done=true;const old=structuredClone(p.scenes);let saved=0;const calls=[];
 await regenerateScene(p,1,{channel,save:async()=>{saved++;},generate:async(action,context)=>{calls.push({action,context});return action==='sceneTags'?{tagsByIndex:[{index:2,expression:bible.expressions[0].tag,pose:bible.poses[0].tag,camera:'wide',graphics:[],summary:'He reacts.'}]}:{scenes:[{...row([main.name]),narration:'AI changed narration',prompt:'A boy reacts.'}]};}});
 assert.equal(saved,1);assert.deepEqual(p.scenes[0],old[0]);assert.deepEqual(p.scenes[2],old[2]);assert.equal(p.scenes[1].narration,old[1].narration);assert.equal(p.scenes[1].index,2);assert.equal(p.scenes[1].prompt,'A boy reacts.');assert.deepEqual(p.approved,[]);assert(!p.done);assert.deepEqual(p.animations,{1:'Move first',3:'Move third'});for(const call of calls){assert.deepEqual(call.context.windows,[{index:2,narration:'Second boy reacts.'}]);assert(!JSON.stringify(call).includes('First boy waits.'));assert(!JSON.stringify(call).includes('Third boy smiles.'));}
 const snapshot=structuredClone(p);await assert.rejects(regenerateScene(p,1,{channel,save:async()=>{},generate:async()=>{throw Error('network');}}),/network/);assert.deepEqual(p,snapshot);
});

test('repair UI change handler saves selected roster names and no-character toggle',async()=>{
 const {updateSceneCharacters}=await import('./public/scene-character.mjs');const source=await readFile('studio/public/app.js','utf8'),begin=source.indexOf("app.addEventListener('change'"),end=source.indexOf('\n});',begin)+4;let handler,saves=0,renders=0,noCharacter=false;const p=project();p.scenes=[{index:1,narration:p.script,...row(['Nam']),invalidCharacters:true}];
 const app={addEventListener:(type,callback)=>{handler=callback;},querySelector:()=>({checked:noCharacter}),querySelectorAll:()=>[{checked:true,value:main.name}]};
 new Function('app','updateSceneCharacters','currentChannel','currentProject','save','render','toast',source.slice(begin,end))(app,updateSceneCharacters,()=>channel,()=>p,async()=>{saves++;},()=>{renders++;},message=>{throw Error(message);});
 await handler({target:{dataset:{sceneCharacter:'0'}}});assert.deepEqual(p.scenes[0].characters,[main.name]);assert(!p.scenes[0].invalidCharacters);noCharacter=true;await handler({target:{dataset:{sceneNoCharacter:'0'}}});assert.deepEqual(p.scenes[0].characters,[]);assert(p.scenes[0].noCharacter);assert.equal(saves,2);assert.equal(renders,2);
});

test('Tich sample preserves all original content except name and sends only roster names to AI',async()=>{
 const {loadTichSample,loadSchoolboySample,initializeProjectRoster,confirmProjectRoster}=await import('./public/roster.mjs');const c={type:'mascot'};const fetcher=async url=>({ok:true,json:async()=>JSON.parse(await readFile('studio/public'+url,'utf8')),text:async()=>readFile('studio/public'+url,'utf8')});
 await loadTichSample(c,fetcher);const t=c.characters[0].bible;assert.equal(t.name,'Tích');assert.deepEqual(['expressions','poses','outfits','props','graphics'].map(key=>t[key].length),[8,8,4,7,9]);const preset=JSON.parse(await readFile('studio/public/tich.preset.json','utf8'));assert.deepEqual({...preset,name:bible.name},bible);const original=await readFile('studio/public/schoolboy-bible.txt','utf8');assert.equal(await readFile('studio/public/tich-bible.txt','utf8'),original.replace('"Cậu bé học sinh"','"Tích"'));
 const p=project();delete p.mainCharacters;delete p.rosterConfirmed;initializeProjectRoster(c,p);p.rosterReviewed=true;confirmProjectRoster(c,p);assert.deepEqual(Object.keys(p.roster),['Tích']);const calls=[];await runSceneBatches(p,{channel:c,save:async()=>{},generate:async(action,context)=>{calls.push({action,context});return action==='sceneTags'?{tagsByIndex:[{index:1,expression:t.expressions[0].tag,pose:t.poses[0].tag,camera:'wide',summary:''}]}:{scenes:[row(['Tích'])]};}});for(const call of calls){assert.deepEqual(call.context.rosterNames,['Tích']);assert(!JSON.stringify(call).includes(t.identity));assert(!('research' in call.context));assert(!('sources' in call.context));}assert(scenePromptRows(c,p)[0].image_prompt.includes(t.identity));await loadSchoolboySample(c,fetcher);assert.equal(c.characters[0].name,'Cậu bé học sinh');
});
